import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  OneToMany,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import { Exclude } from 'class-transformer';
import { Task } from '../../tasks/entities/task.entity';

/**
 * WHY THIS FILE EXISTS
 * --------------------
 * Maps the `users` table. Kept in its own file (rather than inline in
 * a service) so TypeORM's migration generator can introspect it, and so
 * other modules (Auth, Tasks) can import a single source of truth for
 * the User shape.
 */
@Entity('users')
export class User {
  // UUID primary key - generated by PostgreSQL's pgcrypto/uuid-ossp
  // extension via TypeORM's 'uuid' generation strategy.
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'varchar', length: 255 })
  name: string;

  // Emails must be unique across the whole table - enforced both here
  // (DB constraint) and in AuthService (friendly 409 before hitting DB).
  @Index({ unique: true })
  @Column({ type: 'varchar', length: 255, unique: true })
  email: string;

  // `@Exclude()` (class-transformer) ensures the hashed password is
  // stripped out whenever a User entity is serialised in an HTTP
  // response, e.g. via ClassSerializerInterceptor or plainToInstance.
  @Exclude()
  @Column({ type: 'varchar' })
  password: string;

  // Nullable - a user can exist without ever uploading a profile photo.
  @Column({ type: 'varchar', nullable: true, default: null })
  profilePicture: string | null;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt: Date;

  // One user can own many tasks. `() => Task` is a lazy reference to
  // avoid a circular-import crash between user.entity.ts and
  // task.entity.ts.
  @OneToMany(() => Task, (task) => task.user)
  tasks: Task[];
}
